// Code generated by microgen 0.10.0. DO NOT EDIT.

package transport

import (
	"context"
	"fmt"
	endpoint "github.com/go-kit/kit/endpoint"
	metrics "github.com/go-kit/kit/metrics"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
	"time"
)

// EndpointsSet implements PersonService API and used for transport purposes.
type EndpointsSet struct {
	CreatePersonEndpoint   endpoint.Endpoint
	UpdatePersonEndpoint   endpoint.Endpoint
	DeletePersonEndpoint   endpoint.Endpoint
	GetPersonByIdEndpoint  endpoint.Endpoint
	GetPersonsByIdEndpoint endpoint.Endpoint
	FindPersonsEndpoint    endpoint.Endpoint
}

func InstrumentingEndpoints(endpoints EndpointsSet, tracer opentracinggo.Tracer) EndpointsSet {
	return EndpointsSet{
		CreatePersonEndpoint:   opentracing.TraceServer(tracer, "CreatePerson")(endpoints.CreatePersonEndpoint),
		DeletePersonEndpoint:   opentracing.TraceServer(tracer, "DeletePerson")(endpoints.DeletePersonEndpoint),
		FindPersonsEndpoint:    opentracing.TraceServer(tracer, "FindPersons")(endpoints.FindPersonsEndpoint),
		GetPersonByIdEndpoint:  opentracing.TraceServer(tracer, "GetPersonById")(endpoints.GetPersonByIdEndpoint),
		GetPersonsByIdEndpoint: opentracing.TraceServer(tracer, "GetPersonsById")(endpoints.GetPersonsByIdEndpoint),
		UpdatePersonEndpoint:   opentracing.TraceServer(tracer, "UpdatePerson")(endpoints.UpdatePersonEndpoint),
	}
}

func LatencyMiddleware(dur metrics.Histogram, methodName string) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		dur := dur.With("method", methodName)
		return func(ctx context.Context, request interface{}) (response interface{}, err error) {
			defer func(begin time.Time) {
				dur.With("success", fmt.Sprint(err == nil)).Observe(time.Since(begin).Seconds())
			}(time.Now())
			return next(ctx, request)
		}
	}
}

func RequestFrequencyMiddleware(freq metrics.Gauge, methodName string) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		freq := freq.With("method", methodName)
		return func(ctx context.Context, request interface{}) (interface{}, error) {
			freq.Add(1)
			response, err := next(ctx, request)
			freq.Add(-1)
			return response, err
		}
	}
}
