// Code generated by microgen 0.10.0. DO NOT EDIT.

package service

import service "github.com/valerylobachev/microgen/examples/person/api"

// Service middleware (closure).
type Middleware func(service.PersonService) service.PersonService
