// Code generated by microgen 0.10.0. DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	log "github.com/go-kit/kit/log"
	service "github.com/valerylobachev/microgen/examples/person/api"
)

// RecoveringMiddleware recovers panics from method calls, writes to provided logger and returns the error of panic as method error.
func RecoveringMiddleware(logger log.Logger) Middleware {
	return func(next service.PersonService) service.PersonService {
		return &recoveringMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type recoveringMiddleware struct {
	logger log.Logger
	next   service.PersonService
}

func (M recoveringMiddleware) CreatePerson(ctx context.Context, payload service.CreatePersonPayload) (err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "CreatePerson", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.CreatePerson(ctx, payload)
}

func (M recoveringMiddleware) UpdatePerson(ctx context.Context, payload service.UpdatePersonPayload) (err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "UpdatePerson", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.UpdatePerson(ctx, payload)
}

func (M recoveringMiddleware) DeletePerson(ctx context.Context, payload service.DeletePersonPayload) (err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "DeletePerson", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.DeletePerson(ctx, payload)
}

func (M recoveringMiddleware) GetPersonById(ctx context.Context, id string, source string) (res *service.Person, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "GetPersonById", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.GetPersonById(ctx, id, source)
}

func (M recoveringMiddleware) GetPersonsById(ctx context.Context, ids []string, source string) (res []service.Person, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "GetPersonsById", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.GetPersonsById(ctx, ids, source)
}

func (M recoveringMiddleware) FindPersons(ctx context.Context, query service.FindPersonQuery) (res []service.Person, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "FindPersons", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.FindPersons(ctx, query)
}
