// Code generated by microgen 0.10.0. DO NOT EDIT.

package service

import service "github.com/valerylobachev/microgen/examples/usersvc/pkg/usersvc"

// Service middleware (closure).
type Middleware func(service.UserService) service.UserService
