// Code generated by microgen 0.10.0. DO NOT EDIT.

package service

import service "github.com/valerylobachev/microgen/examples/addsvc/addsvc"

// Service middleware (closure).
type Middleware func(service.Service) service.Service
